### PR TITLE
Use errorcode values from the sdk rather than our own consts

### PR DESCRIPTION
**Pull request by stilvoid**
*Issue #, if available:* N/A

*Description of changes:* Use handler error codes from the SDK rather than add new constants.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brianterry** [comment]
If we make this change, how does the end user know which handler error codes are valid? For example, if they return a progressEvent, the errorCode type is a string so they could assign any value to that type. Although Cloudformation is looking for a certain error code when a specific type of error happens.  for example, in the Cloudformation CLI Contract test, one of the test is looking for a `handler.NotFound` code when a resource is not found.

Is it any way we could use a type instead of a string as a guardrail?

**Comment by sthulb** [comment]
I'm ok with this – if a user wants to shoot themselves in the foot, they can :)

**Comment by brianterry** [comment]
Ok, I'll approval also. But we need to add some documentation about what valid errors can be return.

**Comment by stilvoid** [comment]
> Ok, I'll approval also. But we need to add some documentation about what valid errors can be return.

Agreed. I've added a comment to the docs for handler.ProgressEvent. That should be enough to have it appear in IDEs.

**Pull request merged**
